# Generated by Django 4.0.4 on 2022-06-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comments_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='author_email',
            field=models.EmailField(default='example@email.com', max_length=254),
        ),
    ]
