# Generated by Django 4.0.4 on 2022-06-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comments_author_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='full_text',
            new_name='review_text',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='preview',
        ),
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.CharField(default='anonymous', max_length=30, verbose_name='Name'),
        ),
    ]
