# Generated by Django 4.0.4 on 2022-06-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='image_serv',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
