# Generated by Django 4.0.3 on 2022-04-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Travel request', max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('convenient_time_to_call', models.CharField(max_length=100)),
                ('travel_type', models.CharField(choices=[('a', 'All tours'), ('d', 'Day tours'), ('g', 'Guided tours'), ('r', 'Road trips'), ('s', 'Special offer')], max_length=1)),
                ('travel_services', models.CharField(blank=True, choices=[('c', 'Car rental'), ('a', 'Accommodation'), ('f', 'Flights')], max_length=1)),
                ('activities', models.TextField(blank=True, max_length=150)),
                ('attractions', models.TextField(blank=True, max_length=150)),
                ('comments', models.TextField(blank=True, max_length=150)),
                ('sign_up_for_our_mailing_list', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=1)),
                ('issued', models.DateTimeField()),
            ],
        ),
    ]
